using System.Collections.Generic;

namespace GK2Coop
{
    internal static partial class L
    {
        private static void AddGerman(Dictionary<string, Dictionary<string, string>> tables)
        {
            tables["de"] = new Dictionary<string, string>
            {
                // Main menu and the co-op window
                ["Co-op"] = "Koop",
                ["Play in one world together. One player hosts, the others join."] = "Spielt gemeinsam in einer Welt. Einer hostet, die anderen treten bei.",
                ["Host a game"] = "Spiel hosten",
                ["Join a game"] = "Spiel beitreten",
                ["Cancel"] = "Abbrechen",
                ["Co-op is off. Your next game is single player."] = "Koop ist aus. Dein nächstes Spiel ist ein Einzelspieler-Spiel.",
                ["Version {0}"] = "Version {0}",
                ["Your next game is hosted on Steam."] = "Dein nächstes Spiel wird über Steam gehostet.",
                ["Your next game is hosted on port {0}."] = "Dein nächstes Spiel wird auf Port {0} gehostet.",
                ["Your next game joins a Steam friend."] = "Mit deinem nächsten Spiel trittst du einem Steam-Freund bei.",
                ["Your next game joins {0}."] = "Mit deinem nächsten Spiel trittst du {0} bei.",
                ["Your name"] = "Dein Name",
                ["Players"] = "Spieler",
                ["Host on Steam"] = "Über Steam hosten",
                ["Done. Load a game and your friends can join. Press {0} in game to invite them."] = "Fertig. Lade ein Spiel, dann können deine Freunde beitreten. Mit {0} lädst du sie im Spiel ein.",
                ["Friends join from their Steam friends list or through an invite."] = "Freunde treten über ihre Steam-Freundesliste oder eine Einladung bei.",
                ["Host without Steam"] = "Ohne Steam hosten",
                ["Others connect to this PC. That works on the same network, over a VPN such as Tailscale, or over the internet if your router forwards the port."] =
                    "Die anderen verbinden sich mit diesem PC. Das klappt im selben Netzwerk, über ein VPN wie Tailscale oder übers Internet, wenn dein Router den Port weiterleitet.",
                ["Port"] = "Port",
                ["Show my addresses"] = "Meine Adressen zeigen",
                ["Hide my addresses"] = "Meine Adressen verbergen",
                ["Copy"] = "Kopieren",
                ["Address copied."] = "Adresse kopiert.",
                ["Host"] = "Hosten",
                ["Done. Load a game, then give the others your address."] = "Fertig. Lade ein Spiel und gib den anderen deine Adresse.",
                ["Home network"] = "Heimnetz",
                ["No usable address found."] = "Keine nutzbare Adresse gefunden.",
                ["Friends hosting now"] = "Freunde, die gerade hosten",
                ["None right now. You can also accept an invite in Steam."] = "Gerade niemand. Du kannst auch eine Einladung in Steam annehmen.",
                ["Join"] = "Beitreten",
                ["Join by address"] = "Über Adresse beitreten",
                ["Address"] = "Adresse",
                ["Enter the host's address first."] = "Gib zuerst die Adresse des Hosts ein.",
                ["You play in a copy of the host's world. Your own saves are not touched."] = "Du spielst in einer Kopie der Welt des Hosts. Deine eigenen Spielstände bleiben unberührt.",
                ["Join without copying"] = "Ohne Kopie beitreten",
                ["Only when you both have the same save."] = "Nur wenn ihr beide denselben Spielstand habt.",
                ["Done. Load the same save as the host to join {0}."] = "Fertig. Lade denselben Spielstand wie der Host, um {0} beizutreten.",
                ["Back"] = "Zurück",
                ["Select"] = "Wählen",
                ["Recent"] = "Zuletzt",
                ["Type"] = "Eingabe",
                ["Space"] = "Leerzeichen",
                ["Delete"] = "Löschen",
                ["{0} is working here."] = "{0} arbeitet hier gerade.",
                ["{0} is fighting."] = "{0} kämpft gerade.",
                ["You were brought back from the fight area."] = "Du wurdest aus dem Kampfgebiet zurückgebracht.",
                ["The host has co-op mod {0}, you have {1}. Both players need the same version."] = "Der Host hat den Koop-Mod {0}, du hast {1}. Beide Spieler brauchen dieselbe Version.",
                ["The host has a different co-op mod version; you have {0}. Both players need the same version."] = "Der Host hat eine andere Version des Koop-Mods, du hast {0}. Beide Spieler brauchen dieselbe Version.",
                ["The host has no loaded save slot. Save the game first, then retry."] = "Der Host hat keinen geladenen Spielstand. Speichere zuerst und versuche es dann erneut.",
                ["The host is already sending a save to another player."] = "Der Host sendet gerade einem anderen Spieler seinen Spielstand.",
                ["{0} won the fight."] = "{0} hat den Kampf gewonnen.",
                ["{0} lost the fight."] = "{0} hat den Kampf verloren.",
                ["{0}'s fight is over."] = "Der Kampf von {0} ist vorbei.",
                ["Invite friends"] = "Freunde einladen",
                ["Write a message"] = "Nachricht schreiben",
                ["Quick message"] = "Schnellnachricht",
                ["Watch {0}'s scene"] = "Szene von {0} ansehen",
                ["Come here!"] = "Komm her!",
                ["Look at this!"] = "Schau mal!",
                ["Wait for me!"] = "Warte auf mich!",
                ["Thanks!"] = "Danke!",
                ["Yes."] = "Ja.",
                ["No."] = "Nein.",
                ["I'm going to sleep."] = "Ich gehe schlafen.",
                ["Change your look"] = "Aussehen ändern",
                ["Show name tags"] = "Namensschilder zeigen",
                ["Hide name tags"] = "Namensschilder ausblenden",
                ["Show the status"] = "Status zeigen",
                ["Hide the status"] = "Status ausblenden",
                ["Close"] = "Schließen",

                // Joining: copying the host's world
                ["Copying the host's world…"] = "Die Welt des Hosts wird kopiert …",
                ["Could not copy the host's world."] = "Die Welt des Hosts konnte nicht kopiert werden.",
                ["Connecting to {0}…"] = "Verbinde mit {0} …",
                ["Copying the host's world ({0}%)…"] = "Die Welt des Hosts wird kopiert ({0} %) …",
                ["World copied. Loading it…"] = "Welt kopiert. Sie wird geladen …",
                ["Could not start a connection to {0}."] = "Die Verbindung zu {0} konnte nicht gestartet werden.",
                ["Could not reach the host at {0}. Make sure they are hosting and already in their world. Over the internet, their router has to forward port {1}."] =
                    "Der Host unter {0} ist nicht erreichbar. Er muss hosten und schon in seiner Welt sein. Übers Internet muss sein Router den Port {1} weiterleiten.",
                ["The host stopped sending the world. Check the connection and try again."] = "Der Host sendet die Welt nicht mehr. Prüfe die Verbindung und versuche es erneut.",
                ["Could not read the host's world: {0}"] = "Die Welt des Hosts konnte nicht gelesen werden: {0}",
                ["Could not import the host's world: {0}"] = "Die Welt des Hosts konnte nicht übernommen werden: {0}",
                ["Could not load the host's world: {0}"] = "Die Welt des Hosts konnte nicht geladen werden: {0}",

                // Session status
                ["Connecting…"] = "Verbinde …",
                ["Could not connect"] = "Verbindung fehlgeschlagen",
                ["Connection refused"] = "Verbindung abgelehnt",
                ["Hosting"] = "Du hostest",
                ["Waiting for players…"] = "Warte auf Mitspieler …",
                ["With {0}"] = "Mit {0}",
                ["In {0}'s world"] = "In der Welt von {0}",
                ["Ping {0} ms"] = "Ping {0} ms",
                ["(in {0})"] = "(in {0})",

                // Announcements
                ["{0} joined."] = "{0} ist beigetreten.",
                ["{0} left."] = "{0} hat das Spiel verlassen.",
                ["{0} could not join: they have co-op mod {1}, you have {2}. You both need the same version."] =
                    "{0} konnte nicht beitreten: Koop-Mod {1} statt {2}. Ihr braucht beide dieselbe Version.",
                ["You joined {0}'s game."] = "Du bist dem Spiel von {0} beigetreten.",
                ["The host turned you away. {0}"] = "Der Host hat dich abgewiesen. {0}",
                ["The host has a different version of the co-op mod. You both need the same version."] = "Der Host hat eine andere Version der Koop-Mod. Ihr braucht beide dieselbe Version.",
                ["Could not join. {0}"] = "Beitritt fehlgeschlagen. {0}",
                ["Could not reach {0}:{1}. Make sure the host is hosting. Over the internet, port {1} has to be forwarded to their PC."] =
                    "{0}:{1} ist nicht erreichbar. Der Host muss hosten. Übers Internet muss der Port {1} an seinen PC weitergeleitet werden.",
                ["No reply from the host. Trying again ({0} of {1})…"] = "Keine Antwort vom Host. Neuer Versuch ({0} von {1}) …",
                ["Welcome back. Your inventory and progress are restored."] = "Willkommen zurück. Dein Inventar und dein Fortschritt sind wieder da.",
                ["You start with a fresh inventory."] = "Du startest mit einem neuen Inventar.",
                ["Your inventory could not be restored. You have the host's copy for now."] = "Dein Inventar konnte nicht wiederhergestellt werden. Vorerst hast du die Kopie des Hosts.",
                ["Everyone is asleep. The night passes."] = "Alle schlafen. Die Nacht vergeht.",
                ["Waiting for everyone to sleep."] = "Warte, bis alle schlafen.",
                ["The night passes when"] = "Die Nacht vergeht, wenn",
                ["Everyone sleeps"] = "Alle schlafen",
                ["I sleep"] = "Ich schlafe",
                ["Your sleep passes the night for everyone. The others' clock jumps ahead with yours."] = "Dein Schlaf lässt die Nacht für alle vergehen. Die Uhr der anderen springt mit deiner vor.",
                ["You sleep. The night passes for everyone."] = "Du schläfst. Die Nacht vergeht für alle.",
                ["{0} is asleep. The night passes."] = "{0} schläft. Die Nacht vergeht.",
                ["You sleep and recover. The night only passes when everyone sleeps."] = "Du schläfst und erholst dich. Die Nacht vergeht erst, wenn alle schlafen.",
                ["A friend invited you. Go back to the main menu to join."] = "Ein Freund hat dich eingeladen. Geh zurück ins Hauptmenü, um beizutreten.",
                ["Joining {0}…"] = "Trete {0} bei …",
                ["Joining your friend…"] = "Trete deinem Freund bei …",
                ["Could not enter your friend's game ({0})."] = "Das Spiel deines Freundes ist nicht erreichbar ({0}).",
                ["That Steam game is not a co-op session."] = "Dieses Steam-Spiel ist keine Koop-Sitzung.",
                ["Your friend's co-op mod does not match yours. You both need the same release."] = "Die Koop-Mod deines Freundes passt nicht zu deiner. Ihr braucht beide dieselbe Version.",
                ["Your friend has co-op mod {0}, you have {1}. You both need the same version."] = "Dein Freund hat Koop-Mod {0}, du hast {1}. Ihr braucht beide dieselbe Version.",
                ["Inviting works while you host on Steam."] = "Einladen geht, während du über Steam hostest.",
                ["Co-op mod {0} was installed from the Workshop. Restart the game to use it."] = "Koop-Mod {0} wurde aus dem Workshop installiert. Starte das Spiel neu, um sie zu nutzen.",
                ["Could not install the co-op mod update from the Workshop: {0}"] = "Das Update der Koop-Mod aus dem Workshop konnte nicht installiert werden: {0}",

                // Chat and the status window
                ["Say:"] = "Sagen:",
                ["A scene is starting"] = "Eine Szene beginnt",
                ["{0} is watching a scene."] = "{0} schaut eine Szene.",
                ["Watching together."] = "Ihr schaut gemeinsam.",
                ["You keep playing."] = "Du spielst weiter.",
                ["Closes in {0} s."] = "Schließt in {0} s.",
                ["Watch"] = "Mitschauen",
                ["Keep playing"] = "Weiterspielen",
                ["Watching a scene"] = "Du schaust zu",
                ["Stop watching"] = "Nicht mehr zuschauen",
                ["Hosting co-op in Graveyard Keeper 2"] = "Hostet Koop in Graveyard Keeper 2",
                ["Waiting for players on port {0}."] = "Warte auf Mitspieler auf Port {0}.",
                ["Connected to {0}."] = "Verbunden mit {0}.",
                ["Connecting"] = "Verbinden",
                ["Copying the world"] = "Welt wird kopiert",
                ["Loading the world"] = "Welt wird geladen",
                ["Together"] = "Zusammen",
                ["Something went wrong"] = "Etwas ist schiefgelaufen",
                ["Could not reach {0} over Steam. Make sure they are hosting and already in their world, then try again."] =
                    "Über Steam ist der Host ({0}) nicht erreichbar. Er muss hosten und schon in seiner Welt sein; dann erneut versuchen.",
                ["your friend"] = "dein Freund",
                ["Your friend's game is not open to join right now. If they are hosting, try again in a moment."] = "Das Spiel deines Freundes ist gerade nicht offen zum Beitreten. Wenn er hostet, versuche es gleich noch einmal.",
                ["The session has ended"] = "Die Sitzung ist beendet",
                ["The connection to {0}'s game has ended. Nothing you do from here on is saved. OK takes you back to the main menu, where you can join again."] =
                    "Die Verbindung zum Spiel von {0} ist beendet. Was du ab jetzt tust, wird nicht gespeichert. OK bringt dich zurück ins Hauptmenü, wo du erneut beitreten kannst.",
                ["OK"] = "OK",
            };
        }
    }
}
