[CmdletBinding()]
param(
    [string]$GamePath = 'C:\Program Files (x86)\Steam\steamapps\common\Graveyard Keeper 2',
    [string]$Configuration = 'Release',
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$artifactRoot = Join-Path $projectRoot 'artifacts'
$bepInExStage = Join-Path $artifactRoot 'bepinex-5.4.23.5'
$projectFile = Join-Path $projectRoot 'src\GK2Coop\GK2Coop.csproj'
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    # A fixed channel name, not a version claim. Seven scripts and the guest-side installer
    # reference this filename; the real version is in the DLL, the manifest, and printed below.
    $OutputPath = Join-Path $artifactRoot 'GK2Coop-0.1.0-dev.zip'
}

$gameExe = @('GraveyardKeeper2.exe', 'GraveyardKeeper2Demo.exe') | ForEach-Object { Join-Path $GamePath $_ } | Where-Object { Test-Path -LiteralPath $_ -PathType Leaf } | Select-Object -First 1
if (-not $gameExe) { throw "No supported Graveyard Keeper 2 executable found in $GamePath" }
# Only this copy's own process matters (the build reads its assemblies); another copy, such as
# someone playing from the Steam install while this builds against a test copy, is left alone.
if (@(Get-Process -Name ([IO.Path]::GetFileNameWithoutExtension($gameExe)) -ErrorAction SilentlyContinue | Where-Object { $_.Path -and [string]::Equals($_.Path, $gameExe, [StringComparison]::OrdinalIgnoreCase) }).Count -gt 0) {
    throw "Close $gameExe before building the package."
}
if (-not (Test-Path -LiteralPath (Join-Path $bepInExStage 'winhttp.dll') -PathType Leaf)) {
    throw 'The staged BepInEx 5.4.23.5 distribution is missing.'
}

dotnet build $projectFile -c $Configuration -p:GamePath="$GamePath" -p:BepInExPath="$bepInExStage"
if ($LASTEXITCODE -ne 0) {
    throw 'Plugin build failed.'
}

$packageStage = Join-Path $artifactRoot ('package-stage-' + [guid]::NewGuid().ToString('N'))
$resolvedArtifactRoot = [IO.Path]::GetFullPath($artifactRoot).TrimEnd([IO.Path]::DirectorySeparatorChar) + [IO.Path]::DirectorySeparatorChar
$resolvedPackageStage = [IO.Path]::GetFullPath($packageStage)
if (-not $resolvedPackageStage.StartsWith($resolvedArtifactRoot, [StringComparison]::OrdinalIgnoreCase)) {
    throw "Refusing to use a package staging path outside the artifact directory: $resolvedPackageStage"
}

try {
    New-Item -ItemType Directory -Force -Path (Join-Path $packageStage 'BepInEx\core') | Out-Null
    New-Item -ItemType Directory -Force -Path (Join-Path $packageStage 'BepInEx\plugins\GK2Coop') | Out-Null
    New-Item -ItemType Directory -Force -Path (Join-Path $packageStage 'BepInEx\config') | Out-Null

    foreach ($loaderFile in @('.doorstop_version', 'changelog.txt', 'doorstop_config.ini', 'winhttp.dll')) {
        Copy-Item -LiteralPath (Join-Path $bepInExStage $loaderFile) -Destination (Join-Path $packageStage $loaderFile)
    }
    Get-ChildItem -LiteralPath (Join-Path $bepInExStage 'BepInEx\core') -File | ForEach-Object {
        Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $packageStage 'BepInEx\core')
    }
    Copy-Item -LiteralPath (Join-Path $projectRoot "src\GK2Coop\bin\$Configuration\net472\GK2Coop.dll") -Destination (Join-Path $packageStage 'BepInEx\plugins\GK2Coop\GK2Coop.dll')
    # No settings file: BepInEx writes the defaults on first start (they match
    # package\com.fabio.gk2coop.cfg, as for the Workshop item), and a player extracting an update
    # over an older install keeps their name, Steam choice and players instead of the defaults.
    Copy-Item -LiteralPath (Join-Path $projectRoot 'package\INSTALL.txt') -Destination (Join-Path $packageStage 'INSTALL-GK2COOP.txt')
    # The same guide in every language the game has (generated by tests\Generate-Guides.py).
    $guideStage = Join-Path $packageStage 'GK2Coop-Guides'
    New-Item -ItemType Directory -Force -Path $guideStage | Out-Null
    Get-ChildItem -LiteralPath (Join-Path $projectRoot 'package\guides') -Filter 'INSTALL-GK2COOP.*.txt' | ForEach-Object {
        Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $guideStage $_.Name)
    }
    # The mod's license, and the licenses of BepInEx and its libraries (Doorstop's LGPL in full).
    Copy-Item -LiteralPath (Join-Path $projectRoot 'LICENSE') -Destination (Join-Path $packageStage 'LICENSE.txt')
    Copy-Item -LiteralPath (Join-Path $projectRoot 'THIRD-PARTY-NOTICES.txt') -Destination (Join-Path $packageStage 'THIRD-PARTY-NOTICES.txt')
    New-Item -ItemType Directory -Force -Path (Join-Path $packageStage 'third-party') | Out-Null
    Copy-Item -LiteralPath (Join-Path $projectRoot 'third-party\UnityDoorstop-LICENSE.txt') -Destination (Join-Path $packageStage 'third-party\UnityDoorstop-LICENSE.txt')

    if (Test-Path -LiteralPath $OutputPath -PathType Leaf) {
        $backupDir = Join-Path $artifactRoot 'package-backups'
        New-Item -ItemType Directory -Force -Path $backupDir | Out-Null
        $oldHash = (Get-FileHash -LiteralPath $OutputPath -Algorithm SHA256).Hash.Substring(0, 12)
        Copy-Item -LiteralPath $OutputPath -Destination (Join-Path $backupDir ("$(Split-Path -Leaf $OutputPath).$oldHash.bak")) -Force
        Remove-Item -LiteralPath $OutputPath -Force
    }
    Compress-Archive -Path (Join-Path $packageStage '*') -DestinationPath $OutputPath -CompressionLevel Optimal
}
finally {
    if (Test-Path -LiteralPath $resolvedPackageStage -PathType Container) {
        Remove-Item -LiteralPath $resolvedPackageStage -Recurse -Force
    }
}

$packageHash = (Get-FileHash -LiteralPath $OutputPath -Algorithm SHA256).Hash
$pluginVersion = ([xml](Get-Content -LiteralPath $projectFile)).Project.PropertyGroup.Version |
    Where-Object { $_ } | Select-Object -First 1
Write-Host "Created package: $OutputPath"
Write-Host "Plugin version: $pluginVersion (the file name is a fixed channel name, not a version)"
Write-Host "SHA256: $packageHash"
